import pandapower as pp
import pandas as pd
import pandapower.plotting as plot

def build_grid() -> pp.pandapowerNet:
  net = pp.create_empty_network(name="Central Valley Agricultural Microgrid")

  # create buses:
  # Bus 1: utility connection
  # Bus 2: solar PV
  # Bus 3: battery storage
  # Bus 4: irrigation pump
  bus_1 = pp.create_bus(net, vn_kv=12.47, name="Bus 1 - Utility")
  bus_2 = pp.create_bus(net, vn_kv=12.47, name="Bus 2 - Solar")
  bus_3 = pp.create_bus(net, vn_kv=12.47, name="Bus 3 - Battery")
  bus_4 = pp.create_bus(net, vn_kv=12.47, name="Bus 4 - Irrigation")

  # Create optional geographic positions for plotting
  net["bus_geodata"] = pd.DataFrame(
      index=net.bus.index,
      columns=["x", "y"],
      dtype=float,
  )

  # Fixed positions for the visual diagram
  net.bus_geodata.loc[bus_1, ["x", "y"]] = [0, 0]
  net.bus_geodata.loc[bus_2, ["x", "y"]] = [1, 0]
  net.bus_geodata.loc[bus_3, ["x", "y"]] = [2, 0]
  net.bus_geodata.loc[bus_4, ["x", "y"]] = [3, 0]

  # Utility grid connection:
  pp.create_ext_grid(net, bus=bus_1, vm_pu=1.00, name="Utility Connection")
  
  # Distribution lines connecting to the buses
  line_parameters = {
    "length_km": 1.0,
    "r_ohm_per_km": 0.20,
    "x_ohm_per_km": 0.08,
    "c_nf_per_km": 0.0,
    "max_i_ka": 0.40,
  }

  pp.create_line_from_parameters(
    net,
    from_bus=bus_1,
    to_bus=bus_2,
    name="Line 1-2",
    **line_parameters,
  )

  pp.create_line_from_parameters(
    net,
    from_bus=bus_2,
    to_bus=bus_3,
    name="Line 2-3",
    **line_parameters,
  )

  pp.create_line_from_parameters(
    net,
    from_bus=bus_3,
    to_bus=bus_4,
    name="Line 3-4",
    **line_parameters,
  )

  # Solar PV generation:
  pp.create_sgen(
    net,
    bus=bus_2,
    p_mw=0.15,
    q_mvar=0.0,
    name="Solar PV"
  )

  # Battery energy storage
  pp.create_storage(
    net,
    bus=bus_3,
    p_mw=0.0,
    max_e_mwh=0.20,
    soc_percent=50.0,
    min_e_mwh=0.0,
    max_p_mw=0.10,
    min_p_mw=-0.10,
    name="Battery Storage",
  )

  # Irrigation pump demand:
  pp.create_load(
    net,
    bus=bus_4,
    p_mw=0.25,
    q_mvar=0.08,
    name="Irrigation Pump",  
  )

  return net


def main() -> None:

  net = build_grid()
  pp.runpp(net)

  print("\nPower flow completed successfully")
  print("\nBus voltages: ")
  print(net.res_bus[["vm_pu", "va_degree"]])

  print("\nLine Loading:")
  print(net.res_line[["loading_percent", "p_from_mw", "p_to_mw"]])
  
  print("\nPower generated by solar PV:")
  print(net.res_sgen[["p_mw", "q_mvar"]])

  print("\nPower consumed by irrigation pump:")
  print(net.res_load[["p_mw", "q_mvar"]])

  import pandapower.plotting as plot
  plot.simple_plot(net, show_plot=True)
  

if __name__=="__main__":
  main()
  
